version: 0.2

phases:
 pre_build:
  commands:
   - echo Logging into Amazon ECR started on `date`
   - aws --version
   - echo Logging into Amazon ECR....
   - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 863518426050.dkr.ecr.ap-south-1.amazonaws.com
   - echo setting repository URI....
   - REPOSITORY_URI=863518426050.dkr.ecr.ap-south-1.amazonaws.com/cicdpipeline
   - echo setting image tag....
   - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

 build:
  commands:
   - echo building the Docker image...
    - docker build -t $REPOSITORY_URI:latest.
    - echo building and tagging started image on `date`
    - echo running mvn clean install...
    - mvn clean install

 post_build:
  commands:
   - echo pushing Docker image to Amazon ECR started on `date`
   - echo pushing to repository...
   - docker push $REPOSITORY_URI:latest
   - docker push $REPOSITORY_URI:$IMAGE_TAG
   - echo setting container name...
   - DOCKER_CONTAINER_NAME=cdcicontainer
   - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
   - echo $DOCKER_CONTAINER_NAME
   - echo printing imagedefinitions.json
   - cat imagedefinitions.json

artifacts:
 files:
  - imagedefinitions.json
